blog/urls.py
from django.urls import path
from . import views

# start with blog
urlpatterns = [
	# http://localhost:8000/blog/1
	path('', views.blog_list, name="blog_list"),
    path('<int:blog_pk>', views.blog_detail, name="blog_detail"),
    path('type<int:blog_type_pk>', views.blogs_with_type, name="blogs_with_type"),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name="blogs_with_date"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path('login_for_modal/', views.login_for_modal, name="login_for_modal"),
    path('login/', views.login, name="login"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout, name="logout"),
    path('user_info/', views.user_info, name="user_info"),
    path('change_nickname/', views.change_nickname, name="change_nickname"),
    path('bind_email/', views.bind_email, name="bind_email"),
    path('send_verfication_code/', views.send_verfication_code, name="send_verfication_code"),
    path('change_password/', views.change_password, name="change_password"),
    path('forgot_password', views.forgot_password, name="forgot_password"),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- 响应式，适应屏幕 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	{% block header_extends %}{% endblock %}
</head>
<body>
	<div class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'home' %}">
					个人博客网站
				</a>
				<button class="navbar-toggle collapsed" data-toggle="collapse" 
				data-target="navbar-collapse">
					<span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
				</button>
			</div>
			<div id="navbar-collapse" class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="{% block nav_home_active %}{% endblock %}">
						<a href="{% url 'home' %}">首页</a>
					</li>
					<li class="{% block nav_blog_active %}{% endblock %}">
						<a href="{% url 'blog_list' %}">博客</a>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					{% if not user.is_authenticated %}		
						<li><a href="{% url 'user:login' %}?from={{ request.get_full_path }}">登录</a></li>
						<li><a href="{% url 'user:register' %}?from={{ request.get_full_path }}">注册</a>	</li>
					{% else %}
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"> 
								{% if user.has_nickname %}
									{{ user.username }}({{ user.get_nickname }}) 
								{% else %}
									{{ user.username }}	
								{% endif %}
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'user:user_info' %}">个人资料</a></li>
								<li><a href="{% url 'user:change_password' %}?from={{ request.get_full_path }}">修改密码</a></li>
								{% if user.is_staff or user.is_superuser %}
									<li><a href="{% url 'admin:index' %}">后台管理</a></li>
								{% endif %}
								<li>
									<a href="{% url 'user:logout' %}?from={{ request.get_full_path }}">退出</a>
								</li>
							</ul>
						</li>
					{% endif %}	
				</ul>
			</div>
		</div>
	</div>
	{% block content %}{% endblock %}
	<!-- Modal -->
		<div class="modal fade" id="login_modal" tabindex="-1" role="dialog">
		  <div class="modal-dialog modal-sm" role="document">
		    <div class="modal-content">
		    	<form id="login_medal_form" action="" method="POST">
			        <div class="modal-header">
			            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			            <h4 class="modal-title">登录</h4>
			        </div>
			        <div class="modal-body">   
						{% csrf_token %}
						{% for field in login_modal_form %}
							<label for="{{ field.id_for_label }}">{{ field.label }}</label>
							{{ field }}
						{% endfor %}
						<span id="login_modal_tip" class="text-danger"></span>
			        </div>
			        <div class="modal-footer">
			        	<button type="submit" class="btn btn-primary">登录</button>
			        	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			        </div>
		        </form>
		    </div>
		  </div>
		</div>
	{% block script_extends %}
		<script type="text/javascript">
			$("#login_medal_form").submit(function(event){
				event.preventDefault();
				$.ajax({
					url: '{% url "user:login_for_modal" %}',
					type: 'POST',
					data: $(this).serialize(),
					cache: false,
					success:function(data){
						if(data['status']=='SUCCESS'){
							window.location.reload();
						}else{
							$('#login_modal_tip').text('用户名或密码不正确');
						}
					},
					error: function(xhr){
						console.log(xhr);
					}
				});
			});
		</script>
	{% endblock %}
</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
	我的网站|错误
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
	<h3>{{ message }}</h3><a href="{{ redirect }}">返回</a>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
	我的网站|首页
{% endblock %}

{% block header_extends %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
	<script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
	<h3 class="home-content">欢迎访问我的网站</h3>
	<!-- 图表容器 DOM -->
    <div id="container"></div>
    <script>
        // 图表配置
        var options = {
            chart: {type: 'line'},
            title: {text: null},
            xAxis: {
                categories: {{ dates|safe }},
                tickmarkPlacement: 'on', 
                title: { 'text': '前7日阅读量变化' },
            },
            yAxis: {
                title: { text: null },
                labels:{ enabled:false },
                gridLineDashStyle: 'Dash',
            },
            series: [{                              // 数据列
                name: '阅读量',                        // 数据列名
                data: {{ read_nums }},                   // 数据
            }],
            plotOptions: {
			    line: {
			        dataLabels: {
			            enabled: true
			        }
			    }
			},
            legend: { enabled:false },
            credits: { enabled:false },
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>
{% endblock %}